### ISSUE TITLE
spork 0.9.0.rc2 fails to start under Windows 7

### ISSUE THREAD

**Issue by jarmo** [sporkrb/spork#74]
When starting spork 0.9.0.rc2 with `spork` then this happens:

```
C:\Users\jarmo\Desktop\minu\projects\Ruby\sample_app>spork
Using RSpec
  -- Starting to fill pool...
     Wait until at least one slave is provided before running tests...
  ** CTRL+BREAK to stop Spork and kill all ruby slave processes **
you must call Spork.using_spork! before starting the server (RuntimeError)
C:/bin/pik/Ruby-187-p302/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/lib/spork/server.rb:25:in `listen'
C:/bin/pik/Ruby-187-p302/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/lib/spork/server.rb:20:in `run'
C:/bin/pik/Ruby-187-p302/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/bin/../lib/spork/runner.rb:75:in `run'
C:/bin/pik/Ruby-187-p302/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/bin/../lib/spork/runner.rb:10:in `run'
C:/bin/pik/Ruby-187-p302/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/bin/spork:10
C:/bin/pik/Ruby-187-p302/bin/spork:19:in `load'
C:/bin/pik/Ruby-187-p302/bin/spork:19
```

With 0.8.4 it seems to work fine.

**Comment by veldtmana** [comment]
I get this problem as well

**Comment by ShaneCourtrille** [comment]
Also having this issue but it's not lying since I'm not calling Spork.using_spork! anywhere.. nor can I find out where I should call it.

**Comment by veldtmana** [comment]
I could not fix it, however, I could get spork working on rails 3 with version 0.8.4

**Comment by timcharper** [comment]
I just pushed Spork 0.9.0.rc3... maybe that will help?  If you can consult Donald Parish https://github.com/Milhouse or Roger Pack https://github.com/rdp they may be able to help.

**Comment by jarmo** [comment]
Unfortunately the problem is still there with 0.9.0.rc3

**Comment by timcharper** [comment]
You will need to solicit help from those involved in developing the windows support for Spork as I am not in a position to provide assistance.

**Comment by voxik** [comment]
Please see https://github.com/timcharper/spork/pull/89 ... however I am still not convinced if that line should not be removed at all ...

**Comment by rdp** [comment]
jarmo does this fix it for you? Apparently if you can figure out how to reproduce it in Linux, you might be able to convince Tim to look at it too :)

**Comment by mraccah** [comment]
I'm getting the same error. Any fix in sight?

**Comment by jarmo** [comment]
Check out the pull request from voxik - it's working for me.

**Comment by dblock** [comment]
I am not seeing the same problem with whatever is in master right now. I would close this.

**Comment by timcharper** [comment]
Thanks!
